Livv tasks
RoduanKD/laravel-livv pull request #5
Opened 2022-11-12 13:11 UTC by farahsamaha

2022-11-12 13:13 UTC, farahsamaha commented
solve some problems and complete i18n tasks

2022-11-25 08:51 UTC, RoduanKD requested changes
@farahsamaha thank you so much for the efforts. can you please upload screenshots of the latest state (in the pull request description) after you're done with the changes I requested?

I think we will be ready for a beta release right after this pull request is done

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/Pages/Admin/Dashboard.vue
> +      <v-card-text> {{ $t('comps.msg2') }}</v-card-text>
please use a new translation file `msgs.js` for such messages. `comps` is shot for components which should only have plural and singular names of a component for example:
```
post: {
  p: 'Posts',
  s: 'post',
}
```

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/Pages/Auth/ConfirmPassword.vue
> +      {{ $t('comps.msg3') }}
same here

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/Pages/Auth/ForgotPassword.vue
> +      {{ $t('comps.msg4') }}
same here

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/Pages/Auth/ForgotPassword.vue
> +          dark
do we need the `dark` attribute? if the button color is `primary` will it make the text white?
please explain why we need this
thanks

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/Pages/Auth/Register.vue
> +        <!-- <v-col
if we don't need it. then it's best to remove it from the code also (with it's according translation keys)

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/Pages/Auth/VerifyEmail.vue
> +      {{ $t('comps.msg5') }}
same here

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/Pages/Auth/VerifyEmail.vue
> +      {{ $t('comps.msg6') }}
same here

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/components/Auth/AuthenticationCardLogo.vue
>        <svg
since this file is showing the same logo in `Logo.vue` I think it's best to include the logo component instead. please consider this one.

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/i18n/messages/ar/comps.js
> -  // example: {
please keep this example. and move the new translations to a new file called `msgs.js`

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/i18n/messages/ar/forms.js
>      new: 'جديد{0}',
make sure there is one space after `{0}`

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/i18n/messages/en/auth.js
> +  alreadyregistered: 'Already registered?',
please use camel casing for the translation keys. this one should be `alreadyRegistered`. the same goes for `passwordConfirmation`

2022-11-25 08:51 UTC, RoduanKD commented on resources/js/pages/Welcome.vue
> +    <v-card evaluation="4">
the property name is `elevation` not ~evaluation~ and please make it 5 (same as `Admin/Dashboard`)
https://vuetifyjs.com/en/components/cards/#usage

2022-11-25 08:51 UTC, RoduanKD commented on routes/web.php
> +    return Inertia::render('Welcome', [
let's stick to using `inertia()` instead of `Inertia::render()`

2022-11-27 18:33 UTC, farahsamaha commented
@RoduanKD 
Thanks for your feedback , I've made the changes you requested and I think we're ready for the beta release.

![download (1)](https://user-images.githubusercontent.com/76728832/204153212-b8cd5a45-2509-4fbf-b902-a39848ba3539.jpg)

2022-11-28 05:01 UTC, farahsamaha commented
![download](https://user-images.githubusercontent.com/76728832/204197582-53a49cea-adf1-4d63-bf17-5b6e00f7953a.jpg)

2022-11-28 05:02 UTC, farahsamaha commented
![download (1)](https://user-images.githubusercontent.com/76728832/204197682-3ce5212f-d8aa-4bb2-80be-eac3e197bcdf.jpg)

2022-11-28 05:02 UTC, farahsamaha commented
![download (2)](https://user-images.githubusercontent.com/76728832/204197710-8d0121dd-7e60-4efd-b0de-0dec85528d2c.jpg)

2022-11-28 05:02 UTC, farahsamaha commented
![download (3)](https://user-images.githubusercontent.com/76728832/204197743-c89ea1a2-56b2-43f5-a5c3-466c63ebcc7f.jpg)

2022-11-28 05:02 UTC, farahsamaha commented
![download (5)](https://user-images.githubusercontent.com/76728832/204197766-99d937c5-b434-4159-9189-c2babbb8b1b9.jpg)

2022-11-28 05:03 UTC, farahsamaha commented
![download (4)](https://user-images.githubusercontent.com/76728832/204197783-7e15e8ee-5d63-409b-8caa-273e46be414b.jpg)

2022-11-28 05:03 UTC, farahsamaha commented
![download (6)](https://user-images.githubusercontent.com/76728832/204197801-d0266697-1c12-4a56-a492-c3415c084b9f.jpg)

2022-11-28 05:03 UTC, farahsamaha commented
![download (7)](https://user-images.githubusercontent.com/76728832/204197836-9d9d743c-7fc7-431d-b313-503e22d738fe.jpg)

2022-11-28 05:03 UTC, farahsamaha commented
![download (8)](https://user-images.githubusercontent.com/76728832/204197862-316b1f86-fd9f-4204-bd28-51797f6b730b.jpg)

2022-12-15 14:35 UTC, merged